# Generated by Django 3.2.13 on 2022-07-04 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_auto_20220704_0001'),
        ('products', '0003_auto_20220704_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cust_ref', models.CharField(blank=True, max_length=16, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vat_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_id', models.CharField(default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Inv_lineitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('qty', models.IntegerField(default=0)),
                ('net_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('vat_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='products.product')),
                ('vat_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_items', to='products.vat_rate')),
            ],
        ),
    ]
