# Generated by Django 3.2.13 on 2022-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_lineitem',
            name='vat_code',
            field=models.CharField(editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
