# Generated by Django 3.2.13 on 2022-06-28 19:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country_code',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
