# Generated by Django 3.2.13 on 2022-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
