# Generated by Django 3.2.13 on 2022-07-04 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220704_0001'),
        ('customers', '0004_alter_customer_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='out_of_use',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Customer_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('bill_freq', models.CharField(choices=[('A', 'Annual'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('B', 'Biennial'), ('Z', 'No')], default='Z', max_length=1)),
                ('last_bill_date', models.DateField()),
                ('next_bill_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='products.product')),
            ],
        ),
    ]
