# Generated by Django 3.2.13 on 2022-06-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, unique=True)),
                ('disp_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('desc', models.CharField(max_length=255, unique=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('recurring_bill', models.CharField(choices=[('A', 'Annual'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('B', 'Biennial'), ('Z', 'No')], default='Z', max_length=1)),
                ('display_rank', models.IntegerField(choices=[(0, 'Normal'), (10, 'Display Order 1'), (20, 'Display Order 2'), (30, 'Display Order 3')], default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.prod_category')),
            ],
        ),
    ]
