# Generated by Django 3.2.13 on 2022-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vat_rate',
            options={'verbose_name_plural': 'VAT Rates'},
        ),
    ]
