# Generated by Django 3.2.13 on 2022-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220704_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_use',
            field=models.BooleanField(default=False),
        ),
    ]
